{% set name = "awacs" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cloudtools/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 530272c49e6af9a692d747b1a41bd303794d08a37e140c50741ca6ccb3dfe981

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - awacs
    - awacs.helpers
    - tests

about:
  home: https://github.com/cloudtools/awacs
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: AWS Access Policy Language creation library
  dev_url: https://github.com/cloudtools/awacs

extra:
  recipe-maintainers:
    - agcopenhaver
    - rluria14
    - oblute
