travis:
  secure:
    BINSTAR_TOKEN: JaEKV/e+cIqFeBcl9LvOMihxm0sjMzzvD9rOVoqxrcfzlyDhShmPIvxtSl3b7+x0Yfm58RSFRvI9GdIMoa9GIsrH7TzqDQ7zj5YBy5Me22yvNabz7rBOLIfbVW3yrTantYKFwFBUnu1E+Ep8x/yELd65xeujbMk1IU5RONa8cHEKAyM+f3n0uZi+TxHtisH4/UNVBWJR5YyJktmGBRWJ7heSFgnPXYYsdoBdqknEk2OqLaw+7JZQMA1PC+vZXq3hu4o6mEvb0qK4Lr9Cx+MPx80vxDsNKmW7J1GHVsqiI1o5eJdNaUeMzch8xrvOCDFoX0De8Pv0olDrs4OP2vRieVPoK7Br2tqPn+3uUgCr2q1WtD7FCK6zdrVsY1bswSMXWnnxQzWzsmWBlAOVadR47S2wyUkfaiAIW86sUQj86dw6IE7Ex77LjEgI5Z7CTHxDcW2VfbWhF71/oyuaglu+wrUoJe8NbgaFBd9c1soRIp0vVU7GU3aWmtfA5INIMw3HJNf47GLfCzbwh4DTT2BjuHtBW5o6AOk2aLGRApLGVBkx+VJ6N+SHqhJRQ+PA6vet7LLSAopXNQvaKQCSo3QKPUmlWRsaqL+tR+sTKmEaJNFbmE0/h+XFvaxteXP9Qf5HmfhMFkH73PiM88L+HqA7tPAHhrI99RGbXH2oBXy3zVw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
